tap "burntsushi/ripgrep", "https://github.com/BurntSushi/ripgrep.git"
tap "romkatv/powerlevel10k"

brew "burntsushi/ripgrep/ripgrep-bin"
brew "tldr"
brew "autojump" 
brew "exa"
brew "bat"
brew "fd"
brew "fzf"
brew "m-cli"
brew "mkcert"
brew "the_silver_searcher"
brew "transcrypt"
brew "fx"
brew "yq"
brew "aria2"
brew "httpie"

brew "nvm"
brew "git"
brew "wget"
brew "jenv"
brew "yarn"
brew "go"
brew "docker-compose"

brew "powerlevel10k"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "docker"
cask "iterm2"
cask "textmate"
cask "jetbrains-toolbox"
cask "postman"
cask "sequel-pro"
cask "sourcetree"
cask "google-chrome"
cask "firefox"
cask "vlc"
cask "spotify"
cask "whatsapp"
cask "telegram"
cask "android-file-transfer"
cask "anaconda"
cask "wireshark"
cask "spectacle"